image: node:latest
services:
  - postgres:latest

variables:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test

cache:
  paths:
  - client/node_modules/
  - server/node_modules/

before_script:
  - yarn global add node-gyp

stages:
  - build
  - test

build_client:
  stage: build
  script:
    - cd client
    - yarn
    - yarn build

lint_server:
  stage: test
  script:
    - cd server
    - yarn
    - yarn eslint .

test_server:
  stage: test
  script:
    - cd server
    - yarn
    - yarn global add sequelize-cli
    - sequelize db:migrate
    - yarn testCI
